/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestionpedidos.gui;

import gestionpedidos.logica.PedidoDAO;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Robert
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());
    
    private DefaultTableModel dtm;
    
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    
    public static PedidoDAO bdPedidos = new PedidoDAO();

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        cambiarIconoApp();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jItemNewPedido = new javax.swing.JMenuItem();
        jItemVerPedidos = new javax.swing.JMenuItem();
        jItemInforme = new javax.swing.JMenuItem();
        jItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane.setViewportView(jTable);

        jMenu.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jMenu.text")); // NOI18N

        jItemNewPedido.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jItemNewPedido.text")); // NOI18N
        jItemNewPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemNewPedidoActionPerformed(evt);
            }
        });
        jMenu.add(jItemNewPedido);

        jItemVerPedidos.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jItemVerPedidos.text")); // NOI18N
        jItemVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemVerPedidosActionPerformed(evt);
            }
        });
        jMenu.add(jItemVerPedidos);

        jItemInforme.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jItemInforme.text")); // NOI18N
        jMenu.add(jItemInforme);

        jItemSalir.setText(org.openide.util.NbBundle.getMessage(PantallaPrincipal.class, "PantallaPrincipal.jItemSalir.text")); // NOI18N
        jMenu.add(jItemSalir);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemNewPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemNewPedidoActionPerformed
        NuevoPedido jDialogNewPedido = new NuevoPedido(this, true);
        jDialogNewPedido.setVisible(true);
        
        refrescarDatosTabla();
    }//GEN-LAST:event_jItemNewPedidoActionPerformed

    private void jItemVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemVerPedidosActionPerformed
        
        refrescarDatosTabla();
    }//GEN-LAST:event_jItemVerPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jItemInforme;
    private javax.swing.JMenuItem jItemNewPedido;
    private javax.swing.JMenuItem jItemSalir;
    private javax.swing.JMenuItem jItemVerPedidos;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    private void refrescarDatosTabla() {
        dtm.setRowCount(0);

        // Si no hay datos en la BD no refresca
        if (bdPedidos.listaPedidos().isEmpty()) {
            return;
        }
        // Recoge los datos de la BD
        bdPedidos.listaPedidos().forEach(p ->
                dtm.addRow(new Object[]{p.getId(), p.getProducto(), p.getCategoria(), p.getPrecioUnitario(), p.getCantidad(), sdf.format(p.getFechaPedido())}));
        
        // Forzar la reordenación
        RowSorter<? extends TableModel> sorter = jTable.getRowSorter();
        if (sorter != null) {
            ((TableRowSorter<?>) sorter).sort();
        }
    }

    /**
     * Inicializa los componentes de la tabla y su ordenación
     */
    private void inicializarTabla() {
        // Inicializar dtm, asegurando que ordena bien al ser un dato Double
        dtm = new DefaultTableModel() {
            @Override
            public Class getColumnClass(int columna) {
                if (columna != 3) {
                } else {
                    return Double.class;
                }
                return Object.class;
            }
        };
        
        String[] titulos = new String[]{"ID", "Producto", "Categoría", "Precio Ud.", "Cantidad", "Fecha"};
        
        dtm.setColumnIdentifiers(titulos);
        
        jTable.setModel(dtm);

        // Sorter
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable.getModel());
        
        jTable.setRowSorter(sorter);

        // Configurar orden
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        // De mayor a menor

        sortKeys.add(
                new RowSorter.SortKey(0, SortOrder.ASCENDING));

        // Aplicamos orden
        sorter.setSortKeys(sortKeys);

        // Refrescamos los datos
        refrescarDatosTabla();
    }

    /**
     * Cambia el icono de la app
     */
    private void cambiarIconoApp() {
        
    }
}
